# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7xCUhZTDTmW28-aJgRCVhoGZl0ZLH2K
"""

import numpy as np
import matplotlib.pyplot as plt

# Definir las ecuaciones
x = np.linspace(-1, 3, 400)
y1 = 2 - 1.0001 * x
y2 = 2 - x

# Crear la gráfica
plt.figure(figsize=(8, 6))
plt.plot(x, y1, label='1.0001x + y = 2', color='r')
plt.plot(x, y2, label='x + y = 2', color='b')

# Encontrar el punto de intersección
A = np.array([[1.0001, 1], [1, 1]])
b = np.array([2, 2])
solution = np.linalg.solve(A, b)

# Graficar el punto de intersección
plt.plot(solution[0], solution[1], 'ko', label='Solución')

# Configurar la gráfica
plt.xlabel('x')
plt.ylabel('y')
plt.title('Gráfica del sistema de ecuaciones')
plt.legend()
plt.grid(True)
plt.show()